# https://docs.gradle.org/current/userguide/version_catalogs.html
[versions]
junit-jupiter = "5.10.2"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
